import { t } from "i18next";
import {
  Globe,
  Smartphone,
  Code,
  Server,
  Layers,
  Palette,
  ShoppingCart,
  FileText,
  Cloud,
  MessageSquare,
  Brain,
  BarChart3,
  PlugZap,
  Gamepad2,
  Monitor,
  Wifi,
  Settings2,
  CloudUpload,
  User,
  GraduationCap,
  Megaphone,
  Edit3,
  Brush,
  Film,
  Camera,
  BadgeCheck,
  Briefcase,
  UsersRound,
  Languages,
  CircleEllipsis,
} from "lucide-react";

export const categories = [
  {
    id: 1,
    name: t("posts.Web-Development"),
    key: "Web Development",
    icon: Globe,
  },
  {
    id: 2,
    name: t("posts.Mobile-Development"),
    key: "Mobile Development",
    icon: Smartphone,
  },
  { id: 3, name: t("posts.Frontend"), key: "Frontend", icon: Code },
  { id: 4, name: t("posts.Backend"), key: "Backend", icon: Server },
  { id: 5, name: t("posts.Fullstack"), key: "Fullstack", icon: Layers },
  { id: 6, name: t("posts.UI-UX"), key: "UI/UX Design", icon: Palette },
  {
    id: 7,
    name: t("posts.Ecommerce"),
    key: "E-commerce",
    icon: ShoppingCart,
  },
  {
    id: 8,
    name: t("posts.Landing-Page"),
    key: "Landing Page",
    icon: FileText,
  },
  { id: 9, name: t("posts.SaaS"), key: "SaaS Project", icon: Cloud },
  {
    id: 10,
    name: t("posts.Chat-App"),
    key: "Chat / Messaging App",
    icon: MessageSquare,
  },
  {
    id: 11,
    name: t("posts.AI-ML"),
    key: "AI / Machine Learning",
    icon: Brain,
  },
  {
    id: 12,
    name: t("posts.Data-Visualization"),
    key: "Data Visualization",
    icon: BarChart3,
  },
  {
    id: 13,
    name: t("posts.API-Development"),
    key: "API Development",
    icon: PlugZap,
  },
  {
    id: 14,
    name: t("posts.Game-Development"),
    key: "Game Development",
    icon: Gamepad2,
  },
  {
    id: 15,
    name: t("posts.Desktop-App"),
    key: "Desktop Application",
    icon: Monitor,
  },
  { id: 16, name: t("posts.IoT-Project"), key: "IoT Project", icon: Wifi },
  {
    id: 17,
    name: t("posts.Automation"),
    key: "Automation System",
    icon: Settings2,
  },
  {
    id: 18,
    name: t("posts.Cloud-Project"),
    key: "Cloud-based Project",
    icon: CloudUpload,
  },
  {
    id: 19,
    name: t("posts.Portfolio-Site"),
    key: "Portfolio Website",
    icon: User,
  },
  {
    id: 20,
    name: t("posts.Educational-App"),
    key: "Educational App",
    icon: GraduationCap,
  },
  {
    id: 21,
    name: t("posts.SMM"),
    key: "Social Media Management",
    icon: Megaphone,
  },
  {
    id: 22,
    name: t("posts.Content-Creation"),
    key: "Content Creation",
    icon: Edit3,
  },
  {
    id: 23,
    name: t("posts.Graphic-Design"),
    key: "Graphic Design",
    icon: Brush,
  },
  {
    id: 24,
    name: t("posts.Video-Editing"),
    key: "Video Editing",
    icon: Film,
  },
  { id: 25, name: t("posts.Photography"), key: "Photography", icon: Camera },
  { id: 26, name: t("posts.Branding"), key: "Branding", icon: BadgeCheck },
  {
    id: 27,
    name: t("posts.Business-Plan"),
    key: "Business Plan & Strategy",
    icon: Briefcase,
  },
  {
    id: 28,
    name: t("posts.Consulting"),
    key: "Consulting",
    icon: UsersRound,
  },
  {
    id: 29,
    name: t("posts.Translation"),
    key: "Translation",
    icon: Languages,
  },
  { id: 30, name: t("posts.Other"), key: "Other", icon: CircleEllipsis },
];
